/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.List;

public class App {

    private static final String FILE = "src/main/resources/gates.js";

    public static void main(String[] args) {

        Linter lint = new Linter();
        List<String> result = lint.linterJS(FILE);

        for(String line: result){
            System.out.println(line);
        }

        System.out.println("Total errors: " + result.size());

    }
}
