/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static basiclibrary.Library.roll;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testRoll() {
        int[] values = new int[]{1,2,3,4};
        assertEquals("array length should be the same", values.length, roll(4).length);
    }

    @Test (expected = IllegalArgumentException.class)
    public void testRollZeroN() {
        roll(0);
    }
}
