/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    private static final int MIN_NUMBER = 1;
    private static final int MAX_NUMBER = 6;


    /**
     * Function to fill out array by rolling six-sided dice.
     * @param n number of times the dice will be rolled
     * @return resulting array with values of rolled dice
     */
    public static int[] roll (int n){
        //Check if n is valid
        if(n <= 0){
            throw new IllegalArgumentException("Number of times should be greater than zero.");
        }
        //result array
        int[] result = new int[n];
        //Loop through the result array and insert random value from 1-6
        for(int index = 0; index < result.length; index++){
            result[index] = (int)(MIN_NUMBER + Math.random() * MAX_NUMBER);
        }

        //return result array
        return result;
    }


    
}
